### ISSUE TITLE
Failed to execute script 'picklescan gui' due to unhandled exception: Found 0 values for STACK GLOBAL at position 0 instead of 2.

### ISSUE THREAD

**Issue by Raz0rStorm** [diStyApps/Stable-Diffusion-Pickle-Scanner-GUI#5]
![image](https://user-images.githubusercontent.com/95212158/207834641-8e7068bb-70d1-4cef-a850-c5dd6437c416.png)

**Comment by diStyApps** [comment]
You just try to run it and this is what happens?
What version?

**Comment by masonj19** [comment]
I run into a similar error if I attempt to scan my entire webui installation directory. I am on version 0.1.5

`Failed to execute script 'run_app_gui' due to unhandled exception: Found 0 values for STACK_GLOBAL at position 0 instead of 2.`

`Traceback (most recent call last):
  File "run_app_gui.py", line 252, in <module>
  File "run_app_gui.py", line 221, in main
  File "run_app_gui.py", line 178, in scan
  File "picklescan\src\picklescan\scanner.py", line 361, in scan_directory_path
  File "picklescan\src\picklescan\scanner.py", line 310, in scan_bytes
  File "picklescan\src\picklescan\scanner.py", line 254, in scan_zip_bytes
  File "picklescan\src\picklescan\scanner.py", line 218, in scan_pickle_bytes
  File "picklescan\src\picklescan\scanner.py", line 207, in _list_globals
ValueError: Found 0 values for STACK_GLOBAL at position 0 instead of 2.`

The error occurs when it tries to process the file at: `stable-diffusion-webui\venv\Lib\site-packages\scipy\fftpack\tests\test.npz`

If try to run that file through in the "file" mode it crashes as well.

I realize that the program is probably not designed to scan this type of file but even so it should be made to skip over it instead of crashing.

I don't know if this is the exact same problem as op, but I hope this helps.

**Comment by firecz** [comment]
> 

I had exactly the same thing - 0.1.15, scanning an entire directory (but nmkd gui), same error on a same file.

**Comment by diStyApps** [comment]
Thank you for using the app. 
I apologize for the inconvenience. To fix the issue, I have temporarily removed support for .npz files. I will fix the issue properly when I have more time. 
The latest version of the app should have resolved the issue in the meantime.
